var CONFIG = {
  spreadsheetId: '1x7RyquXcQ3eFcsGh4R3B7wmCg2XWneHddhtY_nql4mw',
  version: 'v2.0',
  rawSheets: ['RAW_PMS_BOOKINGS','RAW_PMS_ROOMS','RAW_POS_TRANSACTIONS','RAW_POS_SALES_LINES','RAW_FINANCE_GL','RAW_INVENTORY_MOVEMENTS','RAW_PROCUREMENT','RAW_BUDGET','RAW_MANUAL_ADJUSTMENTS'],
  masterSheets: ['MASTER_PROPERTY','MASTER_DEPARTMENT','MASTER_PRODUCT','MASTER_PRODUCT_CATEGORY','MASTER_ACCOUNT','MASTER_CHANNEL','MASTER_CUSTOMER_SEGMENT','MASTER_ROOM_TYPE','MASTER_SUPPLIER','MASTER_MAPPING'],
  stgSheets: ['STG_PMS_BOOKINGS','STG_PMS_ROOMS','STG_POS_TRANSACTIONS','STG_POS_SALES_LINES','STG_FINANCE_GL','STG_INVENTORY','STG_PROCUREMENT','STG_BUDGET'],
  cleanSheets: ['CLEAN_PMS_BOOKINGS','CLEAN_PMS_ROOMS','CLEAN_POS_TRANSACTIONS','CLEAN_POS_SALES_LINES','CLEAN_FINANCE_GL','CLEAN_INVENTORY','CLEAN_PROCUREMENT','CLEAN_BUDGET'],
  analyticsSheets: ['DIM_DATE','DIM_PROPERTY','DIM_ACCOUNT','DIM_PRODUCT','DIM_DEPARTMENT','FACT_ROOM_SALES','FACT_FNB_SALES','FACT_INVENTORY','FACT_PURCHASE','FACT_EXPENSE','FACT_BUDGET','MART_KPI_DAILY'],
  logSheet: '03_ETL_RUN_LOG'
};
